### ISSUE TITLE
Please add support for Windows.

### ISSUE THREAD

**Issue by profpfeff** [geekprojects/lolz#2]
To make this awesome tool more widely useable to others in out team it would be cool if this ran on Windows also.

**Comment by DrFlibble** [comment]
As I don't have any Windows environments available myself, this is unlikely to be done any time soon...

You're welcome to submit pull requests, though :)

**Comment by profpfeff** [comment]
Will poll for interest amonst the others and if there's interest I shall do it.

**Comment by profpfeff** [comment]
Simon has expressed interest.

**Comment by profpfeff** [comment]
Not required
